version: '3.4'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

  webfrontend:
    image: webfrontend
    build:
      context: WebFrontend
      dockerfile: Dockerfile
    volumes:
        - ./WebFrontend/src:/app/src

  webapi:
    image: webapi
    build:
      context: .
      dockerfile: WebApi/Dockerfile