version: '3.4'

services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: WebApi/Dockerfile

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

  webfrontend:
    image: ${DOCKER_REGISTRY-}webfrontend
    build:
      context: WebFrontend
      dockerfile: Dockerfile
    volumes:
        - ./WebFrontend/src:/app/src